name: Update README with Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Stats and Update README
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # Replace placeholders in README with actual token
          sed -i "s/YOUR_PERSONAL_ACCESS_TOKEN/$GH_PAT/g" README.md

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest stats'
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
